### ISSUE TITLE
メインカラーに名前をつける

### ISSUE THREAD

**Issue by hanaori** [mekke-me/mekke#23]
![image](https://cloud.githubusercontent.com/assets/7506598/23359960/2510e546-fd2c-11e6-8d34-159a5fead6d1.png)

**Comment by okuramasafumi** [comment]
http://stackoverflow.com/questions/8887824/persisting-scss-variables-in-rails-asset-pipeline

```sass
# application.css.scss
@import "colors";

# colors.scss
$mekkeRed #FF6347;
```

こんな感じで定義すると、変数がグローバルになります。
